# Generated by Django 5.2.3 on 2025-06-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original filename of the uploaded PDF.', max_length=255, unique=True)),
                ('text_content', models.TextField(help_text='Extracted text content from the PDF.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the paper was uploaded.')),
            ],
            options={
                'verbose_name': 'Paper Summary',
                'verbose_name_plural': 'Paper Summaries',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalizedPaperSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('summary_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_summaries', to='papers.papersummary')),
            ],
            options={
                'unique_together': {('paper_summary', 'language')},
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text="The user's question about the paper.", max_length=500)),
                ('answer', models.TextField(blank=True, help_text='The answer generated by Gemini for the question.', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the question was answered.')),
                ('answer_language', models.CharField(default='Russian', help_text="Language of the answer (e.g., 'Russian', 'Uzbek').", max_length=10)),
                ('paper_summary', models.ForeignKey(help_text='The paper this question and answer relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers', to='papers.papersummary')),
            ],
            options={
                'verbose_name': 'Question Answer',
                'verbose_name_plural': 'Question Answers',
                'ordering': ['answered_at'],
                'unique_together': {('paper_summary', 'question', 'answer_language')},
            },
        ),
    ]
