# Generated by Django 5.2.3 on 2025-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersummary',
            name='authors',
            field=models.TextField(blank=True, help_text='Authors extracted from the PDF metadata.', null=True),
        ),
        migrations.AddField(
            model_name='papersummary',
            name='title',
            field=models.TextField(blank=True, help_text='Title extracted from the PDF metadata.', null=True),
        ),
    ]
