# Generated by Django 5.2.3 on 2025-06-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_papersummary_authors_papersummary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersummary',
            name='url',
            field=models.URLField(blank=True, help_text='URL to the original paper (e.g., ArXiv link).', null=True),
        ),
    ]
