# Generated by Django 5.2.3 on 2025-06-13 05:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_papersummary_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localizedpapersummary',
            options={'verbose_name': 'Localized Paper Summary', 'verbose_name_plural': 'Localized Paper Summaries'},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ['-asked_at'], 'verbose_name': 'Question Answer', 'verbose_name_plural': 'Question Answers'},
        ),
        migrations.AlterUniqueTogether(
            name='localizedpapersummary',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='answered_at',
        ),
        migrations.AddField(
            model_name='localizedpapersummary',
            name='summary_type',
            field=models.CharField(choices=[('ordinary', 'Ordinary Summary'), ('short', 'Short Summary'), ('detailed', 'Detailed Summary')], default='ordinary', help_text='Type of summary (e.g., short, ordinary, detailed).', max_length=20),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='asked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='paper_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers', to='papers.papersummary'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='localizedpapersummary',
            unique_together={('paper_summary', 'language', 'summary_type')},
        ),
    ]
