# Generated by Django 5.0.3 on 2025-06-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_alter_localizedpapersummary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersummary',
            name='file_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
