# Generated by Django 5.0.3 on 2025-06-13 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_alter_papersummary_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localizedpapersummary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ['answered_at'], 'verbose_name': 'Question Answer', 'verbose_name_plural': 'Question Answers'},
        ),
        migrations.AlterUniqueTogether(
            name='localizedpapersummary',
            unique_together={('paper_summary', 'language')},
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='asked_at',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the question was answered.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papersummary',
            name='file_name',
            field=models.CharField(help_text='Original filename of the uploaded PDF.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(blank=True, help_text='The answer generated by Gemini for the question.', null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_language',
            field=models.CharField(default='Russian', help_text="Language of the answer (e.g., 'Russian', 'Uzbek').", max_length=10),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='paper_summary',
            field=models.ForeignKey(help_text='The paper this question and answer relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers', to='papers.papersummary'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.CharField(help_text="The user's question about the paper.", max_length=500),
        ),
        migrations.RemoveField(
            model_name='localizedpapersummary',
            name='summary_type',
        ),
    ]
