# Generated by Django 5.0.3 on 2025-06-13 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_alter_localizedpapersummary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localizedpapersummary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Локализованный summary статьи', 'verbose_name_plural': 'Локализованные summaries статей'},
        ),
        migrations.AlterModelOptions(
            name='papersummary',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Summary статьи', 'verbose_name_plural': 'Summaries статей'},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ['answered_at'], 'verbose_name': 'Вопрос и ответ', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.AlterUniqueTogether(
            name='localizedpapersummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='localizedpapersummary',
            name='summary_type',
            field=models.CharField(choices=[('short', 'Короткий'), ('ordinary', 'Стандартный'), ('detailed', 'Подробный')], default='ordinary', help_text='Тип summary (короткий, стандартный или подробный).', max_length=20),
        ),
        migrations.AlterField(
            model_name='localizedpapersummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Временная метка создания summary.'),
        ),
        migrations.AlterField(
            model_name='localizedpapersummary',
            name='language',
            field=models.CharField(help_text="Код языка summary (например, 'ru', 'en', 'uz').", max_length=10),
        ),
        migrations.AlterField(
            model_name='localizedpapersummary',
            name='paper_summary',
            field=models.ForeignKey(help_text='Статья, к которой относится этот summary.', on_delete=django.db.models.deletion.CASCADE, related_name='localized_summaries', to='papers.papersummary'),
        ),
        migrations.AlterField(
            model_name='localizedpapersummary',
            name='summary_text',
            field=models.TextField(help_text='Текст сгенерированного summary.'),
        ),
        migrations.AlterField(
            model_name='localizedpapersummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Временная метка последнего обновления summary.'),
        ),
        migrations.AlterField(
            model_name='papersummary',
            name='authors',
            field=models.TextField(blank=True, help_text='Авторы, извлеченные из метаданных PDF.', null=True),
        ),
        migrations.AlterField(
            model_name='papersummary',
            name='file_name',
            field=models.CharField(help_text='Оригинальное имя файла загруженного PDF.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='papersummary',
            name='text_content',
            field=models.TextField(help_text='Извлеченный текст из PDF.'),
        ),
        migrations.AlterField(
            model_name='papersummary',
            name='title',
            field=models.TextField(blank=True, help_text='Название, извлеченное из метаданных PDF.', null=True),
        ),
        migrations.AlterField(
            model_name='papersummary',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Временная метка загрузки статьи.'),
        ),
        migrations.AlterField(
            model_name='papersummary',
            name='url',
            field=models.URLField(blank=True, help_text='URL оригинальной статьи (например, ссылка на ArXiv).', null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(blank=True, help_text='Ответ, сгенерированный Gemini на вопрос.', null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_language',
            field=models.CharField(default='ru', help_text="Код языка ответа (например, 'ru', 'uz', 'en').", max_length=10),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Временная метка ответа на вопрос.'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='paper_summary',
            field=models.ForeignKey(help_text='Статья, к которой относятся вопрос и ответ.', on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers', to='papers.papersummary'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.CharField(help_text='Вопрос пользователя о статье.', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='localizedpapersummary',
            unique_together={('paper_summary', 'language', 'summary_type')},
        ),
    ]
