# Generated by Django 5.0.3 on 2025-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_alter_localizedpapersummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersummary',
            name='pdf_download_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка для загрузки PDF файла.', max_length=500, null=True),
        ),
    ]
