# Generated by Django 5.0.3 on 2025-06-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_papersummary_pdf_download_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papersummary',
            name='pdf_download_url',
        ),
    ]
